In [14]:
import pandas as pd 
import numpy as np

## Group BY

In [15]:
data = {
    "category": ["Electronics", "Clothing", "Groceries", "Electronics", "Electronics"],
    "store": ["Store A", "Store B", "Store C", "Store A", "Store B"],
    "sales": [15000, 8000, 3000, 22000, 12000],
    "quantity": [5, 20, 50, 8, 25],
    "date": [
        "2026-03-01",
        "2026-03-02",
        "2026-03-03",
        "2026-03-04",
        "2026-03-05"
    ]
}
df=pd.DataFrame(data)
cat=df.groupby('category')
cat 
for i,v in cat:
    print(i)
    print(v)

Clothing
   category    store  sales  quantity        date
1  Clothing  Store B   8000        20  2026-03-02
Electronics
      category    store  sales  quantity        date
0  Electronics  Store A  15000         5  2026-03-01
3  Electronics  Store A  22000         8  2026-03-04
4  Electronics  Store B  12000        25  2026-03-05
Groceries
    category    store  sales  quantity        date
2  Groceries  Store C   3000        50  2026-03-03

In [16]:
#total sales of diff categories
cat=df.groupby('category')['sales'].sum()
cat

category
Clothing        8000
Electronics    49000
Groceries       3000
Name: sales, dtype: int64

In [17]:
#total for for store
store=df.groupby('store')['sales'].sum()
store

store
Store A    37000
Store B    20000
Store C     3000
Name: sales, dtype: int64

In [18]:
# group by multiple column
cat=df.groupby(['category','store'])['sales'].sum()
cat

category     store
Clothing     Store B     8000
Electronics  Store A    37000
             Store B    12000
Groceries    Store C     3000
Name: sales, dtype: int64

## Aggrigation

In [19]:
# mean  ,meadian,std div,min max,count etc.
# mode is not agg function .
df['sales'].mean()

12000.0

In [20]:
df['sales'].agg(['mean','min','std'])

mean    12000.000000
min      3000.000000
std      7176.350047
Name: sales, dtype: float64

## Pivot table

In [22]:

data = {
    "Date": [
        "2025-01-01", "2025-01-02", "2025-01-03",
        "2025-01-04", "2025-01-05", "2025-01-06",
        "2025-01-07", "2025-01-08"
    ],
    "Product": [
        "Laptop", "Laptop", "Tablet", "Tablet",
        "Phone", "Phone", "Laptop", "Tablet"
    ],
    "Region": [
        "North", "South", "East", "West",
        "North", "South", "East", "West"
    ],
    "Sales": [
        1200, 1500, 800, 900,
        600, 700, 1300, 850
    ],
    "Units": [
        3, 4, 5, 6,
        10, 12, 2, 4
    ],
    "Rep": [
        "Alice", "Bob", "Charlie", "David",
        "Alice", "Bob", "Charlie", "David"
    ]
}

df = pd.DataFrame(data)
df['Date'] = pd.to_datetime(df['Date'])
df['month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
print(df)

        Date Product Region  Sales  Units      Rep    month Quarter
0 2025-01-01  Laptop  North   1200      3    Alice  January      Q1
1 2025-01-02  Laptop  South   1500      4      Bob  January      Q1
2 2025-01-03  Tablet   East    800      5  Charlie  January      Q1
3 2025-01-04  Tablet   West    900      6    David  January      Q1
4 2025-01-05   Phone  North    600     10    Alice  January      Q1
5 2025-01-06   Phone  South    700     12      Bob  January      Q1
6 2025-01-07  Laptop   East   1300      2  Charlie  January      Q1
7 2025-01-08  Tablet   West    850      4    David  January      Q1

## Cross table

In [24]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product  Laptop  Phone  Tablet
Region
East     1300.0    NaN   800.0
North    1200.0  600.0     NaN
South    1500.0  700.0     NaN
West        NaN    NaN   875.0

In [26]:
pivot2=pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')

## Cross Table

In [ ]:
# crosstab used for counting purose
pd.crosstab(df['Region'],df['Product'])

Product  Laptop  Phone  Tablet
Region
East          1      0       1
North         1      1       0
South         1      1       0
West          0      0       2